language: cpp

addons:
  homebrew:
    packages:
      - gcc@7

matrix:
  include:
    - os: osx
      name: "macOS with GCC"
      osx_image: xcode10.1

script:
  - git clone "https://github.com/spack/spack"
  - cd spack
  - git checkout v0.12.1
  - . share/spack/setup-env.sh
  - spack install --verbose --jobs 2 boost %gcc
