language: cpp

addons:
  homebrew:
    packages:
      - gcc@7

matrix:
  include:
    - os: osx
      name: "macOS with GCC"
      osx_image: xcode10.1

script:
  - export CC=gcc-7 && export CXX=g++-7 && export PREFIX=workspace/destdir && export BOOST_VER=boost_1_69_0
  - curl -L --output $BOOST_VER.tar.bz2 https://dl.bintray.com/boostorg/release/1.69.0/source/$BOOST_VER.tar.bz2
  - tar xjf $BOOST_VER.tar.bz2
  - cd $BOOST_VER
  - mkdir -p $PREFIX
  - ./bootstrap.sh --prefix=$PREFIX --with-toolset=cc
  - ../user-config.sh
  - ./b2 -j2 --layout=system install
